version: '3.9'

services:
  challenge:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    command: /bin/bash -c "while sleep 1000; do :; done"
    working_dir: /home/dev
    env_file: 
      - .env
    networks:
      - challenge-network
    volumes:
      - ./:/home/dev:cached
      
  dbms:
    build:
      context: ./
      dockerfile: ./dbms/Dockerfile.db
    restart: always
    env_file: 
      - .env
    ports:
      - "3309:3306"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
    name: challenge-network