FROM node:18
# Forcer le faite d'utiliser les miroirs français quand on utilise apt ...
# Attention, le chemin source est rélative à l'emplacement du fichier docker-compose
COPY ./docker/sources.list /etc/apt/sources.list

# Créer l'utilisateur et son groupe, installer des paquets
RUN apt-get update \        
    && apt-get install -y sudo \
    && apt-get install -y less \
    && apt-get install -y mycli \
    && apt-get install -y tzdata \    
    && npm install -g typescript \
    && npm install -g ts-node

# Fixer le fuseau horaire
ENV TZ Europe/Paris

# L'interprète par défaut
ENV SHELL /bin/bash

# Le repertoire maison par défaut
WORKDIR /home/dev

# Using CMD to source environment variables and execute the SQL script on container startup
# CMD /bin/bash -c "sleep 5 && docker exec -i dbms mysql -u root -p"$MYSQL_ROOT_PASSWORD" < /home/dev/database.sql && /bin/bash"
CMD /bin/bash -c "sleep 5 && docker exec -i mycli -u root -p MYSQL_ROOT_PASSWORD -h dbms < /home/dev/database.sql && /bin/bash"